### ISSUE TITLE
RedAPI TODO

### ISSUE THREAD

**Issue by ghost** [genkimarshall/bigredapp-android#1]
Link to [API](http://redapi-tious.rhcloud.com/).
- [x] All menu requests seem to work, except the Jansen's Dining Room one
- [x] Make the calendar API work like the menu API, where one can pass in either a comma-separated list or an ALL keyword to get all calendars in one request
- [x] Have the calendar API able to get multiple days, so for example can do smart things with time (late at night, show tomorrow's breakfast)

**Comment by lidavidm** [comment]
Have you seen projects like http://square.github.io/retrofit/? Seems like they could make this pretty simple. There's also Volley, in the android source itself, but according to http://instructure.github.io/blog/2013/12/09/volley-vs-retrofit/ RetroFit is waaay faster.

**Comment by ghost** [comment]
At first glance, Retrofit does seem really nice and clean. Bookmarked to look at it more later tonight. I would be totally up for a move if it fits our needs!

**Comment by ghost** [comment]
Update, see #14

**Comment by mrkev** [comment]
The issue with Jansen's/Bethe is on redapi. Will fix it this weekend 👍🏽

**Comment by ghost** [comment]
Thanks again! :+1:

**Comment by mrkev** [comment]
Fixed the bug. New id is "jansens_dining_room_bethe_house".

**Comment by ghost** [comment]
Ah awesome thanks ^_^ closing issue!!
