### ISSUE TITLE
Google Play Store post-release TODO

### ISSUE THREAD

**Issue by ghost** [genkimarshall/bigredapp-android#18]
Once uploaded on the Play Store
- [x] Update README with play store link, and link to https://opensourcecornell.slack.com/signup (alongside mention of IRC)
- [x] Add a version tag
- [x] [note to self - update old Big Red App info to link them to this (if they have Android, else say no longer supported -- and ask about anyone who wants to work on the iOS version!)]
